version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Stockholm
    labels:
      - dependencies

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:15"
      timezone: Europe/Stockholm
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Europe/Stockholm
    labels:
      - dependencies
